root:
  username: fakesudo
  settings:
    ntp: True
    hostname: fakelinux
    locale: 
      - en_US.UTF-8 UTF-8
      - fa_IR UTF-8
    lang: en_US.UTF-8
    timezone: Asia/Tehran
    shell: /usr/bin/fish
    drive:
      blk: /dev/sda
      erase: true
      partitions: # used fdisk conf
        - label: BOOT
          size: +512M
          filesystem: uefi
          number: 1
        
        - label: ROOT 
          size: +40G
          filesystem: linux
          number: 2
        
        - label: HOME
          size: " "
          filesystem: linux
          number: 3

  packages: # official mirror 
  # Base Packages
    - base
    - base-devel
    - linux
    - linux-firmware
    - linux-headers
    - grub
    - efibootmgr
    - networkmanager
    - fish
  services:
    - NetworkManager

user:
  scripts: 
    - name: Copy bin files
      shell: sudo cp ./configs/bin/* /usr/local/bin/

    - name: Copy sth config files
      script: ./configs/conf/copy.sh
    
    - name: Install DevOps.nvim
      shell: "git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && git clone https://github.com/FakeSudo/DevOps.nvim.git ~/.config/nvim/lua/custom"
    
    - name: Config VsCode
      script: ./configs/vscode/install.sh
    
    - name: Config fish
      shell: cp -r ./configs/fish/ ~/.config/

    - name: Config rofi
      shell: cp -r ./configs/rofi/ ~/.config/

    - name: Install fonts
      shell: cp -r ./configs/fonts/ ~/.fonts
    
    - name: Config XDG
      shell: "xdg-user-dirs-update && rm -rf ~/Desktop && xdg-user-dirs-update"

    - name: Copy wallpapers
      shell: cp -r ./configs/wallpapers ~/Pictures/.wallpapers

    - name: set FakeLinux to realase name
      shell: sudo sed -i 's/Arch Linux/Fake Linux/' /etc/os-release

    - name: Install WM
      shell: "cp -r ./configs/chadwm ~/.config/ && cd ~/.config/chadwm/chadwm/ && sudo make install clean"

    - name: Install Terminal
      shell: "git clone https://github.com/siduck/st ~/.config/st --depth 1 && cd ~/.config/st && sudo make install clean"
  
  aurhelper: paru # or yay
  
  packages: # official & aur
    # DM & WM & Other
    - xorg
    - sddm
    - sddm-kcm
    - chili-sddm-theme
    - maim
    - imlib2
    - gd
    - reversal-icon-theme-git
    - dracula-gtk-theme
    - xclip
    - xf86-video-ati
    - xf86-video-amdgpu
    - xf86-video-intel
    - rxfetch
    - vlc
    - polkit-gnome
    - pavucontrol
    - nautilus
    - lxappearance
    - gvfs-mtp
    - feh
    - brave-bin
    - anydesk-bin
    - vazirmatn-fonts
    - pamixer
    - obs-studio
    - zoom
    - slack-desktop
    - telegram-desktop
    - pulseaudio
    - discord
    - rofi
    - xdg-user-dirs
    - wget
    - mcmojave-cursors
    - virtualbox-host-modules-arch
    - unzip
    - unrar
    - windscribe-cli
    - mpd
    - mpc
    - font-manager
    
    # Development Langs & DB & DevTools
    - typescript
    - go
    - dash
    - nodejs-lts-gallium
    - deno
    - php
    - php-dblib
    - php-pgsql
    - php-sqlite
    - nodejs-lts-gallium
    - postgresql
    - mariadb
    - redis
    - nmap
    - docker
    - docker-compose
    - helm
    - jq
    - yq
    - kubeadm
    - kubectl
    - kubectx
    - kubelet
    - mongodb-bin
    - minikube
    - minio-client
    - mongocli-bin
    - nginx
    - ngrok
    - neovim
    - npm
    - python-pip
    - terraform
    - visual-studio-code-bin
    - yarn
    - silicon
    - helm

  services:
    - docker
    - windscribe-cli
    - sddm
    - postgresql
